SELECT 
EMPLOYEEID, 
FIRSTNAME, 
LASTNAME, 
EMAIL, 
JOBTITLE, 
HIREDATE, 
MANAGERID, 
ADDRESS, 
CITY, 
STATE, 
ZIPCODE, 
UPDATED_AT,
CONCAT(FIRSTNAME,' ',LASTNAME) AS EMPLOYEE_NAME
FROM
{{ source('landing','employees') }}